spring:
  application:
    name: crm

  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

paypal:
  api-key: 19d8f7dfs07g90sd7fg87sdf90g879d8f7gd9s78fg

stripe:
  apiKey: kldsjflskdjflksdjflkdsjf
  timeout: 1000
  enable: true
